MainBundle\Entity\User:
    type: entity
    repositoryClass: MainBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        score:
            type: integer
            nullable: false
        lead:
            type: boolean
            nullable: false
        reject:
            type: boolean
            nullable: false
    oneToOne:
        medium:
            targetEntity: Medium
            mappedBy: user
            cascade: ['all']
    lifecycleCallbacks: {  }
