main:
    resource: "@MainBundle/Resources/config/routing.yml"
    prefix:   /
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_registration_confirmed:
    pattern: /registration/confirmed
    defaults: { _controller: MainBundle:Main:registrationConfirmed }
    requirements:
        _method: GET