medium_index:
    path:     /
    defaults: { _controller: "MainBundle:Medium:index" }
    methods:  GET

medium_show:
    path:     /{id}/show
    defaults: { _controller: "MainBundle:Medium:show" }
    methods:  GET

medium_new:
    path:     /new
    defaults: { _controller: "MainBundle:Medium:new" }
    methods:  [GET, POST]

medium_edit:
    path:     /{id}/edit
    defaults: { _controller: "MainBundle:Medium:edit" }
    methods:  [GET, POST]

medium_delete:
    path:     /{id}/delete
    defaults: { _controller: "MainBundle:Medium:delete" }
    methods:  DELETE
