<?php

namespace MainBundle\Repository;

use Doctrine\ORM\EntityRepository;
use MainBundle\Entity\Medium;

/**
 * MediumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediumRepository extends EntityRepository
{
	public function findAllbut(Medium $medium)
	{
		$query = $this->createQueryBuilder('m')
			    ->where('m != :leadMedium')
			    ->setParameter('leadMedium', $medium)
			    ->getQuery();
		return $query->getResult();
	}
}
